---
description: 

  T = 25,  p_outcome = 0.6,  outcomepref = 5.0,
  actionpref = 0.0, noactionpref = 1.0,  lr_pA = 0.1,
  expcondition = s_pos_o_zer,
p_outcome: 0.6
outcomepref: 5.0
actionpref: 0.0
noactionpref: 1.0
lr_pA: 0.1
T: 25

showfig: 0
savefig: 0

generative-process:
  expcondition: s_pos_o_zer
  p_outcome_env: 1.0
  p_other_action_env: 0.5

