---
description: 
  preciseA_emotional agent, 
  lower_t = 0, hier_t = 100, 
  impreciseA = 1.0, 
  obj_loc_prior = [4,6], 
  H_threshold = 2.0, 
lower_t: 1
hier_t: 100
impreciseA : 1.0
obj_loc_priors: [4,6]
H_threshold: 2.0
generative-process:
  agent-start: 0
  object-loc: 13
# limiter: true
graph:
  type: generate_connected_clusters
  params:
    - 5
    - 4
